### ISSUE TITLE
Writing ->clj to transit doesn't work 

### ISSUE THREAD

**Issue by roman01la** [mfikes/cljs-bean#70]
```clj
(t/write (t/writer :json) (bean/->clj #js {:hello "world"}))
```

throws
```
writer.js:464 Uncaught Error: Cannot write 
    at Object.writer.maybeQuoted (writer.js:464)
    at Object.writer.marshalTop (writer.js:471)
    at Transit$Writer.writer.Writer.write (writer.js:501)
    at cognitect$transit$write (transit.cljs:278)
    at transit.cljs:8
```

Not sure what is happening there, but happy to dig in and put up a PR.

**Comment by mfikes** [comment]
Repro

```
$ clj -Sdeps '{:deps {com.cognitect/transit-cljs {:mvn/version "0.8.256"} cljs-bean {:mvn/version "1.3.0"}}}' -m cljs.main -re node -r
ClojureScript 1.10.520
cljs.user=> (require '[cognitect.transit :as t] '[cljs-bean.core :as bean])
nil
cljs.user=> (t/write (t/writer :json) (bean/->clj #js {:hello "world"}))
Execution error (Error) at (<cljs repl>:1).
Cannot write

cljs.user=> (pst)
repl:13
throw e__6695__auto__;
^

Error: Cannot write
    at Object.writer.maybeQuoted (/private/var/folders/0b/qr60bz3s1mq0ld2z7t375sgc0000gn/T/out557483901500795328480667167926833/com/cognitect/transit/impl/writer.js:464:23)
    at Object.writer.marshalTop (/private/var/folders/0b/qr60bz3s1mq0ld2z7t375sgc0000gn/T/out557483901500795328480667167926833/com/cognitect/transit/impl/writer.js:471:57)
    at Transit$Writer.writer.Writer.write (/private/var/folders/0b/qr60bz3s1mq0ld2z7t375sgc0000gn/T/out557483901500795328480667167926833/com/cognitect/transit/impl/writer.js:501:26)
    at cognitect$transit$write (/private/var/folders/0b/qr60bz3s1mq0ld2z7t375sgc0000gn/T/out557483901500795328480667167926833/cognitect/transit.js:1001:10)
    at repl:1:113
    at repl:9:3
    at repl:14:4
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Domain.<anonymous> ([stdin]:76:38)
nil
```

**Comment by mfikes** [comment]
It appears that handlers, based on concrete types, must be registered:

```
cljs.user=> (t/write (t/writer :json {:handlers {@#'cljs-bean.core/Bean (t/->MapHandler)}}) (bean/->clj #js {:hello "world"}))
"[\"^ \",\"~:hello\",\"world\"]"
```

**Comment by mfikes** [comment]
I wonder if there is some precedent on good ways to approach this. For example, you can encounter it with `core.rrb-vector`'s non-core vector implementation:

```
(require '[cognitect.transit :as t] '[clojure.core.rrb-vector :as fv])
(t/write (t/writer :json) (fv/vec [1 2 3]))
```

(this yields a similar error)

**Comment by roman01la** [comment]
Thanks!
