### ISSUE TITLE
Question marks in key cause issues with Transit

### ISSUE THREAD

**Issue by martinklepsch** [mfikes/cljs-bean#85]
This works fine:

```clj
(t/write (t/writer :json) {"some-test?" true}))
```

This fails:

```clj
(t/write (t/writer :json) (cljs-bean/->clj #js {"some-test?" true}))
```

```
Error: Cannot write
    at Object.maybeQuoted (compiled/cljs-runtime/com/cognitect/transit/impl/writer.js:469:23)
    at Object.marshalTop (compiled/cljs-runtime/com/cognitect/transit/impl/writer.js:476:57)
    at Transit$Writer.w [as write] (compiled/cljs-runtime/com/cognitect/transit/impl/writer.js:506:26)
    at Object.cognitect$transit$write [as write] (compiled/cljs-runtime/cognitect/transit.cljs:285:11)
    at f (...)
    at compiled/cljs-runtime/promesa/impl.cljc:86:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)⏎
```

Interestingly wrapping the bean in `(take)` also prevents the error:

```clj
(t/write (t/writer :json) (take 1 (cljs-bean/->clj #js {"some-test?" true})))
```

Is this expected?

**Comment by mfikes** [comment]
@martinklepsch I apologize for the embarrassingly late response.

You just need to add `{:handlers (cljs-bean.transit/writer-handlers)}` to the `t/writer` call:

```clj
(t/write (t/writer :json {:handlers (cljs-bean.transit/writer-handlers)}) 
   (cljs-bean/->clj #js {"some-test?" true}))
```

See more at that wonderful site you created: https://cljdoc.org/d/cljs-bean/cljs-bean/1.7.0/doc/transit
